name: Zero
version: '${project.version}'
main: zero.zero.Zero
api-version: 1.19
commands:
  onCommandPvpBow:
    description: command for pvpbow
    usage: /<command>
  onCommandPvpSumo:
    description: command for pvp Sumo
    usage: /<command>
  onCommandPvp:
    description: command for pvp
    usage: /<command>
  onCommandTnt:
    description: command for tnt
    usage: /<command>
  onCommandDontDie:
    description: command for tower of hell
    usage: /<command>
  onCommandPvpKnockBack:
    description: command for pvp knock back
    usage: /<command>
  onCommandPvpLoot:
    description: command for pvp loot
    usage: /<command>
