name: Zero
version: '${project.version}'
main: zero.zero.Zero
api-version: 1.19
commands:
  onCommandLabi:
    description: command for labi
    usage: /<command>
  onCommandBridgeRace:
    description: command for bridge race
    usage: /<command>
  onCommandPvpBow:
    description: command for pvpbow
    usage: /<command>
  onCommandPvpSumo:
    description: command for pvp Sumo
    usage: /<command>
  onCommandPvp:
    description: command for pvp
    usage: /<command>
  onCommandTnt:
    description: command for tnt
    usage: /<command>
  onCommandDontDie:
    description: command for tower of hell
    usage: /<command>
  onCommandPvpKnockBack:
    description: command for pvp knock back
    usage: /<command>
  onCommandPvpLoot:
    description: command for pvp loot
    usage: /<command>
  onCommandParkour:
    description: command for Parkour race
    usage: /<command>
  onCommandCapturFlag:
      description: command for capture the flag
      usage: /<command>
  onCommandChaiseMusical:
      description: command for chaise musical
      usage: /<command>
  onCommandClimbFast:
      description: command for climb fast
      usage: /<command>
  onCommandCpsTest:
    description: command for cps text
    usage: /<command>
  onCommandDodgeBall:
    description: command for dodgeball
    usage: /<command>
  onCommandElytraRace:
    description: command for the elytra race
    usage: /<command>
  onCommandFallTrap:
    description: command for fall trap
    usage: /<command>
  onCommandFindMe:
    description: command for find me aka cherche et trouve
    usage: /<command>
  onCommandFireTrap:
    description: command for fire trap
    usage: /<command>
  onCommandHideAndSeek:
    description: command for hide and seek
    usage: /<command>
  onCommandHorseRace:
    description: command for the horse race
    usage: /<command>
  onCommandMlg:
    description: command for the mlg survival
    usage: /<command>
  onCommandRockPaperCisor:
    description: command for rock paper cisor
    usage: /<command>
  onCommandSkywars:
    description: command for skywars
    usage: /<command>
  onCommandSwimFast:
    description: command for swim fast
    usage: /<command>
  onCommandTag:
    description: command for the tag game
    usage: /<command>